/**
 * ESLint, flat config — ATR-054, the gate `ci.yml` has been promising.
 *
 * The repository went without a linter for a while for a good reason: `lint` was
 * `next lint`, it left with the Next.js stack, and a config written from scratch
 * has to decide what it is *for*. What this one is for is the mistakes this
 * codebase actually makes — and those are not the ones `eslint:recommended`
 * looks for. A codebase whose globals are supplied by three tsconfigs and whose
 * half of everything is Electron IPC handlers does not need `no-undef` guessing
 * at what exists; it needs TypeScript-aware rules, which is why the rule set
 * below is `typescript-eslint`'s recommended set and nothing else.
 *
 * Two deliberate omissions, so nobody has to guess why they are missing:
 *
 *   - **No type-aware rules.** `recommendedTypeChecked` needs a project service,
 *     which means handing ESLint the same tsconfig graph `tsc` already walks,
 *     and it costs a second of lint per file. It is worth adding — `no-floating-
 *     promises` would find real bugs in this app — but it is a bigger change
 *     than "there is now a linter", and the rules that need it can be turned on
 *     in one place when somebody wants to pay for them.
 *   - **No Prettier, no stylistic rules.** Formatting is not what went wrong
 *     here, and a rule set that reformats 236 files on the day it lands is a
 *     rule set that gets reverted.
 *
 * It also adds one thing to the linter's defaults, because it is a failure this
 * repository has already had: a suppression that suppresses nothing is an
 * **error**. Twenty-seven `eslint-disable` comments were left behind by the
 * Next-era linter, each naming a rule that had left with it, and nothing noticed
 * until the linter was rebuilt and they were read by hand. A dead suppression is
 * not cosmetics — it reads as a decision somebody made, so the next person keeps
 * the shape it was working around and never learns that the rule was satisfied,
 * or that it no longer exists. Set here rather than passed on the command line,
 * so `pnpm lint`, an editor's ESLint integration and a hook all answer the same.
 *
 * What it does cover, in the same shape a developer runs it:
 *
 *     pnpm lint
 */

import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    ignores: [
      "node_modules/**",
      // Build output and packaged artifacts: nothing here is source, and
      // `build/`, `obj.target/` and friends appear inside them. `**/dist/**`
      // rather than `dist/**` because `mcp/` has one of its own — a minified
      // bundle is thousands of `no-var` findings and not one of them is a
      // mistake anybody made.
      "out/**",
      "release/**",
      "**/dist/**",
      "dist-electron/**",
      ".vitest-results.json",
      // The Freebuff worktrees: other checkouts of this same repository, each
      // with its own `out/` and its own stale sources. Linting them would
      // report a second copy of every finding, in a tree nobody is editing.
      ".freebuff/**",
      // Generated by `scripts/first-launch.mjs` from the one source the DMG's
      // file, the release notes and the CI warning are rendered from, and
      // checked byte-for-byte by `pnpm first-launch:check`. Reformatting it to
      // satisfy a rule would fail that check, so it is not linted at all.
      "src/shared/adhoc-notice.ts",
    ],
  },
  {
    // See the header. `linterOptions` on its own — deliberately not alongside
    // the `ignores` above, because a config object whose only key is `ignores`
    // means "the whole run ignores this", and adding a second key to it changes
    // that meaning rather than extending it.
    linterOptions: {
      reportUnusedDisableDirectives: "error",
    },
  },
  {
    // Everything ESLint reads by default, plus the two TypeScript flavors. The
    // `.mjs` and `.cjs` halves matter: `scripts/` is where the release tools
    // live, and an unused import or a stray `require` there is exactly the kind
    // of thing that reaches a runner before it reaches a reviewer.
    files: ["**/*.js", "**/*.mjs", "**/*.cjs", "**/*.ts", "**/*.tsx"],
    extends: [...tseslint.configs.recommended],
    rules: {
      // A leading underscore is how this codebase says "deliberately unused" —
      // a callback that has to accept an argument it ignores, an interface
      // fulfilled in a test. The rule is worth having; the convention is how it
      // stays useful instead of being suppressed file by file.
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
    },
  },
  {
    // A `.cjs` file is CommonJS, and in CommonJS `require` is not a mistake —
    // it is the only loader there is. The rule stays on everywhere else, where
    // reaching for it is a habit left over from that era; here it would only
    // mean a suppression comment in every file that has to be CommonJS by
    // nature. `scripts/refuse-github.cjs` is the one that matters: `--require`
    // is the only way to install a preload, and that file's job *is* to be one.
    files: ["**/*.cjs"],
    rules: {
      "@typescript-eslint/no-require-imports": "off",
    },
  },
);
