/**
 * The in-app first-launch notice, as the app says it.
 *
 * Generated by `scripts/first-launch.mjs` — **do not edit this file.** That
 * script holds the facts every surface explaining a refused first launch is
 * rendered from, and this is the fourth of them: the `READ-ME-FIRST.txt`
 * inside the DMG, the paragraph the release notes carry, the `::warning::` a
 * certificate-less CI run prints, and the notice
 * `components/layout/adhoc-build-notice.tsx` shows once somebody is inside
 * the app.
 *
 * It is generated rather than imported because its source is a Node script —
 * it reads `node:fs` to compare the DMG's copy — and the renderer is a
 * Chromium bundle with no Node built-ins in it.
 *
 * `pnpm first-launch:write` rewrites it, and `pnpm first-launch:check` fails
 * when it has drifted, which is what stops it becoming a fifth hand-written
 * copy of the same sentences.
 */

export const AD_HOC_NOTICE_TITLE = "macOS asked you to confirm the first launch — here is why";

export const AD_HOC_NOTICE_BODY = "This build is ad-hoc signed and not notarised by Apple, so macOS refused it until you allowed it through System Settings → Privacy & Security → Open Anyway. The same fact is why the app cannot install its own updates: a notarised build removes both steps.";
